#!/bin/bash
sudo -v
sudo -H xterm -title "server1" -hold -e "sudo geth --datadir node1 --port 3000" &
sudo -H xterm -title "server2" -hold -e "sudo geth --datadir node2 --port 3002" &
sleep 3s
sudo -H xterm -title "console1" -hold -e "sudo geth attach ipc:node1/geth.ipc" &
sudo -H xterm -title "console2" -hold -e "sudo geth attach ipc:node2/geth.ipc" &
